networks:
  cloudbuild:
    external: true

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    networks:
      - cloudbuild
    environment:
      POSTGRES_PASSWORD: adminpass
      POSTGRES_USER: postgres
      POSTGRES_DB: keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    networks:
      - cloudbuild
    env_file:
      - ../keycloak/.env
      
    depends_on:
      - postgres
    ports:
      - 9090:8080
    command:
      - start-dev --db-url=jdbc:postgresql:adminpass//postgres/keycloak